-- FS Para executar

CREATE TABLE TALUNO
(
   COD_ALUNO INTEGER NOT NULL,
   HOME VARCHAR(30),
   CIDADE VARCHAR(30),
   CEP VARCHAR(10),
   PRIMARY KEY (COD_ALUNO)
);

 SELECT * FROM TALUNO;

 INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
 VALUES (1,'MARCIO' ,'NOVO HAMBURGO','93000000');

 INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
 VALUES (2,'PAULA','IVOTI','93000000 ');

   INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES(3,'MARIA','SAPARINGA','93000000');

SELECT * FROM TCONTRATO

CREATE SEQUENCE SEQ_CON START WITH 50;

--
MERGE INTO TCONTRATO TCN 
USING (SELECT COD_ALUNO AS ALUNO
  FROM TALUNO)
  ON (TEN.COD_ALUNO = ALUNO)
  WHEN MATCHED THEN -- ENCONTROU O REGISTRO
  UPDATE SET DESCONTO == 44
  WHEN NOT MATCHED THEN -- NÃO ENCONTROU O REGISTRO
 INSERT(TEN.COD_CONTRATO,TCN.DATA,TCN.COD_ALUNO,TCN.DESCONTO,TCN.TOTAL)