


 SELECT * FROM TALUNO;

 --
 SELECT Concat(COD_ALUNO,NOME) FROM TALUNO;

 --
 SELECT COD_ALUNO |' - '|NOME FROM TALUNO;

 --
 SELECT InitCap(NOME) FROM TALUNO;

 --
 SELECT InStr(NOME,'R') FROM TALUNO;

 --
 SELECT NOME, Length (NOME) FROM TALUNO;

 --
    SELECT NOME, LOWER(NOME) FROM TALUNO;

--
 SELECT NOME, UPPER(NOME) FROM TALUNO;

--
SELECT InitCap('JOSE DA SILVA') FROM TALUNO;

--  LEFT - ESQUERDA
SELECT COD_ALUNO, LPad(COD_ALUNO,5,'0') FROM TALUNO;

-- DIREITA
SELECT NOME, SALARIO,RPad(SALARIO,8,'0') FROM TALUNO;

--
SELECT NOME, RPad(NOME,10,'S') FROM TALUNO;

 --   COPIA PARTE DE UM TEXTO
 -- SUBSTR(CAMPO/TEXTO,POSICAO,QTDE DE CARACT )
 SELECT NOME SubStr(NOME,1,3) FROM TALUNO;

  --
 SELECT REPLACE (UPPER(NOME),'R','S') FROM TALUNO

 --
 SELECT SubStr(NOME,Length(NOME),1) FROM TALUNO;

 --
 SELECT SubStr (NOME,Length(NOME)-1,2) FROM TALUNO;

 --
 SELECT NOME, SubStr (NOME,3,Length(NOME)-3) FROM TALUNO;

 --
 SELECT * FROM TALUNO
 WHERE Lower(NOME) = 'MARCIO';

  SELECT * FROM TALUNO
 WHERE UPPER(NOME) = 'MARCIO';

 SELECT * FROM TALUNO
 WHERE Upper(SubStr(CIDADE,1,3)) - 'CAN';

 UPDATE TALUNO SET
 SALARIO = 633.47
 WHERE COD_ALUNO = 1;


 SELECT
 SALARIO,
 REPLACE(SALARIO, ',' , ''),
 RPad(SALARIO,10,'0'),      --ZEROS A DIREITA ATÉ 10 CASAS
 RPad(SALARIO,10,'0'),     --ZEROS A ESQUERDA ATÉ 10 CASAS
 LPad(REPLACE(SALARIO,',',''),10,'0')
 FROM TALUNO;

 --------------------------DATA
 SELECT * FROM DUAL;

 --SYSDATE RETORNA DATA/HORA DO SERVIDOR.
 SELECT SYSDATE FROM DUAL;

 -- ROUND E TRUNC
 SELECT Round(45.925,2), -- 45.93
        Trunc(45,929,2), -- 45.92
        Mod(10,2) AS RESTO_DIVISAO,
        Trunc(1.99),
        Trunc(1.99,2)
  FROM DUAL;

  SELECT * FROM TCONTRATO;

  --FUNCOES DE DATA/HORA
  SELECT DATA, SYSDATE,DATA + 5 FROM TCONTRATO;

  SELECT SYSDATE - DATA AS DIF_DIAS FROM TCONTRATO;

  SELECT Trunc(SYSDATE - DATA) AS DIAS FROM TCONTRATO;

  -- SOMANDO HORAS EM UMA DATA
  SELECT  SYSDATE,SYSDATE + 5 / 24 AS AD_HORAS FROM TCONTRATO;

  --SOMAR MINUTOS
  SELECT SYSDATE,SYSDATE + 15 / 1440 AS ADD_MINUTOS FROM TCONTRATO;

  SELECT SYSDATE + 30 / (3600 * 24) AS ADD SEGUNDOS FROM TCONTRATO;

   -- HORA FICA 00:00:00
   SELECT SYSDATE,Trunc(SYSDATE) FROM DUAL;

   --DIFERENÇA DE MESES ENTRE DATAS
   SELECT MONTHS BETWEEN(SYSDATE,SYSDATE -90) AS DIF_MES FROM DUAL;

   -- ADICIONA MESES
   SELECT ADD MONTHS(SYSDATE,5) AS ADICIONA_MES_DATA FROM DUAL;

   -- PROXIMA DATA A PARTIR DE UM DIA DA SEMANA
   SELECT NEXT DAY(SYSDATE,'QUARTA-FEIRA') AS PROXIMA_QUARTA_DATA FROM DUAL;

-- ULTIMOO DIA DO MES
SELECT LAST DAY (SYSDATE) AS ULTIMO_DIA_MES FROM DUAL,

-- PRIMEIRO DIA DO PROXIMO MES
-- ATÉ DIA 15 DO MES PEGA O PRIMEIRO DIA DO MES UTIL
-- A PARTIR DO DIA 16 RETORNA O PRIMEIRO DIA DO MES ATUAL






