

  SELECT COD_ALUNO, NOME, CIDADE
  FROM TALUNO;

  SELECT COD_ALUNO AS "CODIGO",NOME, AS "NOME DO ALUNO

  SELECT DISTINCT CIDADE,COD_ALUNO
  FROM TALUNO
  ORDER BY CIDADE;

  SELECT NOME AS CLPSD;
  VALOR,
  VALOR/CARGA_HORARIA,
  Round/VALOR/CARGA_HORARIA,2/ AS VALOR_HORA
  FROM TCURSO
  ORDER BY VALOR_HORA;
  -- Apelido de coluna só funciona ex order by

  SELECT BY CIDADE;


  ...
  SELECT NOME AS CURSO,
      VALOR,
      VALOR/CARGA/HORARIA,
      Round(VALOR/CARGA_HORARIA,2) AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA;
  -- Apelido de coluna só funciona ex order by

SELECT * FROM TTCONTRATO;

UPDATE TCONTRATO SET
DESCONTO - NULL
WHERE COD_CONTRATO = 4;

--CALCULO COM COLUNA = NULL
--REPUTADO = NULL
SELECT COD_CONTRATO,
TOTAL,
DESCONTO,
TOTAL + BV1(DESCONTO,0) AS TOTAL_MAIS_DESCONTO
FROM TCONTRATO;

  ..
