    SELECT * FROM TALUNO;

    --  ALTER TABLE TALUNO DROP COLUMN COLUNA;
    ALTER TABLE TALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';

    ALTER TABLE TALUNO ADD SALARIO NUMBER(0,2) DEFAULT 620;

    UPDATE TALUNO SET
    ESTADO = 'AC'
    SALARIO = 250
    WHERE COD_aluno = 1;

    UPDATE TALUNO SET
    ESTADO = 'MT', SALARIO = 2000
    WHERE COD_ALUNO = 2;

    UPDATE TALUNO SET
    ESTADO = 'SP',SALARIO = 800
    WHERE COD_ALUNO = 5;

    SELECT * FROM TALUNO;

    COMMIT;

    SELECT * FROM TALUNO
    WHERE ESTADO <> 'RS'
    AND SALARIO <= 800
    ORDER BY SALARIO DESC;

    INSERT INTO TALUNO(COD_ALUNO, NOME,CIDADE)
    VALUES(SEQ_ALUNO,NEXTVAL,'VALDO','DOIS IRMAOS');


    INSERT INTO TALUNO(COD_ALUNO, NOME,CIDADE)
    VALUES(SEQ_ALUNO,NEXTVAL,'ALDO','QUATRO IRMAOS');

    SELECT * FROM TALUNO;

    UPDATE TALUNO SET
    ESTADO = 'SP',SALARIO = 900,NOME = 'PEDRO'
    WHERE COD_ALUNO = 5;

    SELECT ESTADO,SALARIO,NOME FROM TALUNO
    ORDEY BY ESTADO,SALARIO DESC;

   --31/12/1899 - DATA ZERO
   --01/01/1900 - DATA 1

   ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE = 1000;
   --
   SELECT SYSDATE - SYSDATE = 100 FROM DUAL;

--
UPDATE TCURSO SET
PRE_REQ = 3
WHERE COD_CURSO = 4;

-- CURSOS SEM PRE REQUISITOS
SELECT * FROM TCURSO WHERE PRF_REQ IS NULL

-- CURSOS COM PRE REQUISITOS
SELECT * FROM TCURSO   WHERE PRF_REQ IS NOT NULL

-- PROCEDENCIA DE OPERADORES
-- ()
-- AND
-- OR
SELECT * FROM TCURSO
WHERE VALOR > 1000
AND CARGA HORARIA = 25

SELECT * FROM TCURSO
WHERE (VALOR > 750
OR VALOR < 1000)
AND CARGA_HORARIA = 25;














